const papers=[
 {id:'wbi11-2601',title:'January 2026 — Unit 1',code:'WBI11/01',date:'9 Jan 2026',time:'1h 30m',marks:80,qp:'biology-u1-jan26-qp.pdf',ms:'biology-u1-jan26-ms.pdf'},
 {id:'wbi11a-2601',title:'January 2026 — Unit 1 (01A · separate answer book)',code:'WBI11/01A',date:'9 Jan 2026',time:'1h 30m',marks:80,qp:'biology-u1a-jan26-qp.pdf',ms:'biology-u1a-jan26-ms.pdf'}
];
const qs=[
 {n:'1',marks:5,q:'Complete the description of how substances move through the cell membrane.',scheme:[
  ['phospholipids / phospholipid bilayer / hydrophobic or non-polar fatty acid tails',['phospholipid','bilayer','hydrophobic','non-polar','fatty acid tails']],['facilitated diffusion',['facilitated diffusion']],['active transport',['active transport']],['ATP / carrier proteins / protein pumps / energy',['atp','carrier protein','protein pump','energy']],['endocytosis',['endocytosis']]
 ],note:'Five independent marking points. “Diffusion” alone is not accepted for facilitated diffusion.'},
 {n:'2(a)(i)',marks:1,q:'Whose law can be used to calculate the rate of diffusion?',type:'mcq',options:['A — Benedict’s','B — Fick’s','C — Meselson’s','D — Stahl’s'],correct:'B'},
 {n:'2(a)(ii)',marks:3,q:'Explain how the rate of diffusion through gas exchange surfaces is affected by cystic fibrosis.',scheme:[['thick / sticky mucus is produced',['thick mucus','sticky mucus']],['mucus blocks / narrows / remains in the airways or alveoli',['block','narrow','airway','alveoli','bronchi','bronchiole','trachea']],['reduced oxygen / carbon dioxide concentration gradient',['concentration gradient','oxygen','carbon dioxide']],['reduced rate of diffusion / gas exchange',['rate of diffusion','gas exchange','diffusion']]],cap:3,note:'Award any three. Increased diffusion distance/thicker alveolar walls or reduced alveolar surface area may also be creditworthy.'},
 {n:'2(b)',marks:3,q:'Describe how one named method of prenatal testing can be used to detect cystic fibrosis.',groups:[[['amniocentesis',['amniocentesis']],['amniotic fluid / cells from amniotic fluid',['amniotic fluid','amniotic sac']],['analyse for the CF mutation / faulty allele',['mutation','faulty allele','defective allele']]],[[ 'chorionic villus sampling / CVS',['chorionic villus','cvs']],['placental / chorionic cells or tissue',['placenta','chorion','chorionic villi']],['analyse for the CF mutation / faulty allele',['mutation','faulty allele','defective allele']]],[[ 'PUBS / cordocentesis',['pubs','cordocentesis','percutaneous umbilical']],['blood from the umbilical cord',['blood','umbilical cord']],['analyse for the CF mutation / faulty allele',['mutation','faulty allele','defective allele']]]]},
 {n:'3(a)',marks:1,q:'Name one obesity indicator other than BMI.',alts:['skin fold thickness','waist-to-hip ratio','waist circumference','percentage body fat'],keys:['skin fold','waist to hip','waist-to-hip','waist circumference','waist measurement','percentage body fat']},
 {n:'3(b)(i)',marks:1,q:'Determine the weight category of a person who is 160 cm tall with body mass of 76 kg.',alts:['overweight'],keys:['overweight']},
 {n:'3(b)(ii)',marks:3,q:'Explain how a person with a BMI of 25.2 could change their diet to reduce their risk of coronary heart disease.',scheme:[['reduce cholesterol / saturated fat intake and link this to reduced atheroma formation',['saturated fat','cholesterol','atheroma','plaque','atherosclerosis']],['reduce salt intake and link this to blood pressure / endothelial damage',['salt','blood pressure','endothelial']],['increase antioxidants and link to reduced free radicals',['antioxidant','free radical']],['increase fibre / roughage and link to reduced cholesterol absorption',['fibre','roughage','cholesterol absorption']],['slightly reduce calories / sugar / fat because the person is only slightly overweight',['calorie','sugar','portion','slightly overweight']]],cap:3},
 {n:'4(a)(i)',marks:2,q:'Complete the fruit-fly genotype/phenotype table for eye colour and sex.',scheme:[['all eye colours correctly identified across the genotypes',['red','white']],['all sexes correctly identified across the genotypes',['female','male']]],note:'The official table awards one mark for all colours correct and one for all sexes correct.'},
 {n:'4(a)(ii)',marks:1,q:'In a population of 2000 fruit flies, the ratio of red eyes to white eyes was 4:1. How many had red eyes?',type:'mcq',options:['A — 400','B — 500','C — 1500','D — 1600'],correct:'D'},
 {n:'4(b)',marks:3,q:'Compare and contrast the types of sex chromosomes found in female and male Komodo dragons with those found in humans.',scheme:[['both species have two different types of sex chromosome',['different','sex chromosome']],['both have one sex with two of the same chromosomes and one sex with different chromosomes',['same','different','chromosome']],['Komodo males have identical chromosomes whereas human females have identical chromosomes (or equivalent comparison)',['komodo','male','identical','human','female']]]},
 {n:'5(a)',marks:1,q:'State the meaning of the term risk factor.',scheme:[['a factor / characteristic that increases the likelihood or probability of an event, disease or condition',['factor','characteristic','likelihood','probability','chance','disease','condition']]]},
 {n:'5(b)',marks:1,q:'Which are non-lifestyle risk factors associated with coronary heart disease?',type:'mcq',options:['A — age and diet high in cholesterol','B — age and sex','C — inactivity and diet high in cholesterol','D — sex and inactivity'],correct:'B'},
 {n:'5(c)',marks:2,q:'Describe the relationship between the number of cigarettes smoked per day and the relative risk of CHD.',scheme:[['overall, more cigarettes smoked is associated with greater relative risk of CHD',['increase','positive correlation','greater risk']],['the relationship is non-linear',['non-linear','nonlinear']],['there is a relative risk of CHD even with no smoking',['no smoking','zero cigarettes','without smoking']]],cap:2},
 {n:'5(d)(i)',marks:1,q:'A person smoked 5 cigarettes a day for 12 years. Calculate the mean number of cigarettes smoked per year, using 365.25 days per year.',alts:['1826','1,826'],keys:['1826','1,826']},
 {n:'5(d)(ii)',marks:3,q:'Explain why this person’s perception of their risk of CHD is likely to be different from their actual risk.',scheme:[['may underestimate / misreport / not know the number of cigarettes smoked',['underestimate','under-estimate','lie','not know','misreport']],['may not smoke the same number every day',['same number','each day','every day','not everyday']],['may not know exactly how long they have smoked',['how long','years','duration']],['may not realise how important smoking is as a risk factor',['not realise','risk factor','awareness','education']]],cap:3},
 {n:'6(a)',marks:2,q:'Draw a triglyceride using the glycerol, fatty-acid and ester-bond shapes shown in the paper.',scheme:[['one glycerol, three fatty acids and three bonds are shown',['glycerol','three fatty','3 fatty','three bonds','3 bonds']],['all components are joined together correctly',['joined','attached','ester']]],note:'This is a drawing question. Draw directly on the canvas; AI vision checks the visible structure against the official marking points.'},
 {n:'6(b)',marks:1,q:'Which row is correct for a saturated fatty acid?',type:'mcq',options:['A','B','C','D'],correct:'A'},
 {n:'6(c)(i)',marks:1,q:'Estimate the melting point of a saturated fatty acid with a chain length of ten carbons.',scheme:[['a whole-number estimate between 15 °C and 50 °C',['15','20','25','30','35','40','45','50']]]},
 {n:'6(c)(ii)',marks:4,q:'Comment on the relationships between fatty-acid melting point and carbon number, presence/absence of C=C bonds, and number of C=C bonds.',scheme:[['for saturated fatty acids, melting point increases as chain length / carbon number increases',['chain length','carbon','increase']],['the saturated fatty acids shown are liquid above the relevant temperature threshold',['saturated','liquid']],['no clear relationship between chain length and melting point for the unsaturated fatty acids shown',['unsaturated','no relationship','no correlation']],['saturated fatty acids have higher melting points than unsaturated fatty acids',['saturated','higher','unsaturated']],['melting point decreases as the number of C=C double bonds increases',['double bond','decrease']]],cap:4},
 {n:'6(c)(iii)',marks:1,q:'Which row correctly assigns the melting points 3 °C, −6 °C and −10 °C to canola, peanut and sesame oils?',type:'mcq',options:['A','B','C','D'],correct:'C'},
 {n:'7(a)(i)',marks:1,q:'Which are the products when lactose is digested?',type:'mcq',options:['A — fructose and sucrose','B — galactose and glucose','C — galactose and sucrose','D — glucose and fructose'],correct:'B'},
 {n:'7(a)(ii)',marks:2,q:'Explain why lactase speeds up the rate of digestion of lactose.',scheme:[['lactase / enzymes act as catalysts',['catalyst','catalyse']],['lactase lowers the activation energy',['activation energy']],['this enables glycosidic bonds between glucose and galactose to be broken',['glycosidic','glucose','galactose']]],cap:2},
 {n:'7(b)',marks:1,q:'68% of a world population of 8.1 × 10⁹ people were lactose intolerant. How many people is this, to two significant figures?',type:'mcq',options:['A — 2.59 × 10⁹','B — 2.6 × 10⁹','C — 5.5 × 10⁹','D — 5.51 × 10⁹'],correct:'C'},
 {n:'7(c)',marks:6,q:'Explain why lactase activity changes when it is trapped in alginate beads. Use the pH and temperature graphs in the paper.',level:true,scheme:[['use relevant comparisons from the pH graph, including range/optimum/activity',['ph','optimum','range']],['explain pH effects using H⁺ concentration, R-group ionisation, bonds and active-site shape',['hydrogen ion','r group','bond','active site']],['explain how alginate can stabilise/protect enzyme structure at different pH values',['alginate','stabilise','protect','shape']],['use relevant comparisons from the temperature graph, including optimum/activity',['temperature','optimum']],['explain temperature effects using kinetic energy/collisions and denaturation/R-group vibration',['kinetic energy','collision','denature','vibrate']],['explain how alginate can stabilise the active site / reduce R-group movement at higher temperatures',['alginate','active site','stabilise','movement']]],note:'This is a 6-mark level-of-response question. The AI examiner should judge scientific reasoning, use of both graphs and logical structure, not simply count keywords.'},
 {n:'8(a)(i)',marks:2,q:'Describe two conclusions from the graph showing percentage of living cancer cells after treatment with different concentrations of Sch B.',scheme:[['increasing Sch B concentration decreases the percentage/number of living cancer cells',['increase','concentration','decrease','living cancer']],['an effect is seen only above the lowest concentrations / minimum effective concentration is around 6.25 μmol dm⁻³',['6.25','minimum','effect']],['even the highest concentration does not destroy all cancer cells',['highest','not all','cancer cells']]],cap:2},
 {n:'8(a)(ii)',marks:1,q:'State why DNA synthesis was used to assess the ability of cancer cells to divide.',scheme:[['DNA must be replicated / synthesised before cell division or mitosis',['dna','replicated','replication','synthesis','cell division','mitosis']]]},
 {n:'8(b)(i)',marks:1,q:'Each mouse received 200 μl of a cell suspension at 1 × 10⁷ cells per cm³. Calculate the number of cells injected.',alts:['2 × 10^6','2x10^6','2000000','2,000,000','2 million'],keys:['2 × 10','2x10','2000000','2,000,000','2 million']},
 {n:'8(b)(ii)',marks:1,q:'Suggest what the control group of mice was treated with.',scheme:[['the solvent/liquid used to dissolve the drug, e.g. water or saline',['solvent','water','saline','salt solution','liquid']]]},
 {n:'8(b)(iii)',marks:2,q:'Calculate the actual volume of the tumour from the Sch B-treated mouse using the formula and dimensions in the paper.',scheme:[['correct volume calculation / working using the stated formula',['volume','π','pi','10']],['final value in the accepted range, approximately 600–681 mm³',['600','628','630','650','680','681']]],note:'The official scheme accepts several values because the longest diameter is measured from the printed image.'},
 {n:'8(b)(iv)',marks:2,q:'Explain why the tumour-volume formula may not give accurate values.',scheme:[['tumours are not uniform / regular in shape',['not uniform','irregular','not regular']],['the measured width/length depends on where the measurement is taken',['where','measurement','width','length']],['the ruler/equipment measures only to limited precision in mm',['ruler','mm','precision']],['the formula may not be appropriate for the tumour shape',['formula','appropriate','shape']]],cap:2},
 {n:'8(c)(i)',marks:4,q:'Explain how a DNA mutation can result in glycine being replaced by aspartate in the polypeptide.',scheme:[['the DNA mutation is a substitution',['substitution']],['the change is transcribed/copied into mRNA',['mrna','transcription','copied']],['the altered codon/triplet codes for aspartate',['codon','triplet','aspartate']],['a tRNA carrying aspartate binds to the altered codon',['trna','aspartate','anticodon']],['aspartate is joined into the polypeptide by peptide bonds',['peptide bond','polypeptide','aspartate']]],cap:4},
 {n:'8(c)(ii)',marks:2,q:'Suggest why it is difficult to develop drugs that target only the polypeptide synthesised from the gene with the G12D mutation.',scheme:[['the target site is only one amino acid / aspartate',['one amino acid','aspartate']],['the drug may fail to bind specifically to that aspartate',['bind','aspartate','specific']],['other proteins also contain aspartate',['other proteins','aspartate']],['therefore the drug could affect other proteins',['affect other proteins','other proteins']]],cap:2},
 {n:'9(a)',marks:6,q:'Explain how development of a DVT in the leg can result in death from a pulmonary embolism. Use the diagram and your knowledge of clotting and circulation.',level:true,scheme:[['formation of the leg clot: impaired venous return while sitting, reduced skeletal-muscle pump and blood pooling around valves',['sitting','skeletal muscle','valve','blood flow']],['blood-clotting pathway: platelets/thromboplastin → prothrombin/thrombin → fibrinogen/fibrin → trapped cells',['platelet','thromboplastin','thrombin','prothrombin','fibrin','fibrinogen']],['part of the clot breaks away and travels through veins/vena cava/right side of heart to the pulmonary artery',['breaks','vena cava','right atrium','right ventricle','pulmonary artery']],['embolus blocks pulmonary blood flow so deoxygenated blood cannot reach the lungs for oxygenation',['block','pulmonary','lungs','oxygen']],['reduced oxygen delivery prevents sufficient aerobic respiration/ATP and can cause fatal organ damage',['oxygenated','aerobic respiration','energy','atp','death']]],note:'This is a 6-mark level-of-response question. The official scheme rewards linked explanations across multiple aspects rather than isolated facts.'},
 {n:'9(b)(i)',marks:2,q:'Explain why people taking anticoagulants must monitor their blood clotting time.',scheme:[['if dose is too high, clotting time is too long / blood clots too slowly',['too high','too long','slow']],['this can cause excessive or uncontrolled blood loss / haemorrhage',['blood loss','bleeding','haemorrhage']],['if dose is too low, clotting time is too short / blood clots too quickly',['too low','too short','fast']],['this raises risk of DVT, embolism, stroke or heart attack',['dvt','embolism','stroke','heart attack']]],cap:2},
 {n:'9(b)(ii)',marks:2,q:'Explain why the copper particles will almost stop moving as the blood clots.',scheme:[['the blood/clot becomes thicker, sticky or forms a fibrin mesh',['thicker','sticky','fibrin','mesh']],['this creates resistance or traps the copper particles so they cannot move freely',['resistance','trapped','stuck','movement']]]},
 {n:'9(b)(iii)',marks:1,q:'Determine the blood clotting time in the smartphone recording using the end time shown on the graph.',alts:['19 seconds','19 s','19','19.0'],keys:['19']},
 {n:'9(b)(iv)',marks:2,q:'Suggest why an end time halfway between points A and B was used to determine blood clotting time.',scheme:[['the particles do not all stop moving at exactly the same time / there is no clear single endpoint',['not all','same time','no clear','end point','endpoint']],['there is a large/rapid change in particle movement before movement almost stops',['rapid','large change','decrease','movement']],['the halfway point provides a representative middle/average endpoint',['halfway','midpoint','middle','average','mean','median']]],cap:2},
 {n:'9(b)(v)',marks:2,q:'Comment on the blood clotting times measured using the smartphone and conventional methods.',scheme:[['there is a positive correlation / the two methods give comparable trends',['positive correlation','both increase','comparable']],['the methods do not give exactly the same clotting times',['not same','difference','do not give']],['at lower clotting times the smartphone method records higher values',['lower','smartphone','higher']],['at higher clotting times the smartphone method records lower values',['higher','smartphone','lower']]],cap:2}
];

const cropMap={"qp":{"1":["1-1.png"],"2(a)(i)":["2-a-i-1.png"],"2(a)(ii)":["2-a-ii-1.png"],"2(b)":["2-b-1.png"],"3(a)":["3-a-1.png"],"3(b)(i)":["3-b-i-1.png"],"3(b)(ii)":["3-b-ii-1.png"],"4(a)(i)":["4-a-i-1.png"],"4(a)(ii)":["4-a-ii-1.png"],"4(b)":["4-b-1.png"],"5(a)":["5-a-1.png"],"5(b)":["5-b-1.png"],"5(c)":["5-c-1.png"],"5(d)(i)":["5-d-i-1.png"],"5(d)(ii)":["5-d-ii-1.png"],"6(a)":["6-a-1.png"],"6(b)":["6-b-1.png"],"6(c)(i)":["6-c-i-1.png","6-c-i-2.png"],"6(c)(ii)":["6-c-ii-1.png","6-c-ii-2.png"],"6(c)(iii)":["6-c-iii-1.png"],"7(a)(i)":["7-a-i-1.png"],"7(a)(ii)":["7-a-ii-1.png"],"7(b)":["7-b-1.png"],"7(c)":["7-c-1.png","7-c-2.png","7-c-3.png"],"8(a)(i)":["8-a-i-1.png","8-a-i-2.png"],"8(a)(ii)":["8-a-ii-1.png"],"8(b)(i)":["8-b-i-1.png"],"8(b)(ii)":["8-b-ii-1.png"],"8(b)(iii)":["8-b-iii-1.png"],"8(b)(iv)":["8-b-iv-1.png"],"8(c)(i)":["8-c-i-1.png"],"8(c)(ii)":["8-c-ii-1.png"],"9(a)":["9-a-1.png","9-a-2.png"],"9(b)(i)":["9-b-i-1.png"],"9(b)(ii)":["9-b-ii-1.png","9-b-ii-2.png"],"9(b)(iii)":["9-b-iii-1.png","9-b-iii-2.png"],"9(b)(iv)":["9-b-iv-1.png","9-b-iv-2.png"],"9(b)(v)":["9-b-v-1.png"]},"ms":{"1":["1-1.png"],"2(a)(i)":["2-a-i-1.png"],"2(a)(ii)":["2-a-ii-1.png"],"2(b)":["2-b-1.png"],"3(a)":["3-a-1.png"],"3(b)(i)":["3-b-i-1.png"],"3(b)(ii)":["3-b-ii-1.png"],"4(a)(i)":["4-a-i-1.png"],"4(a)(ii)":["4-a-ii-1.png"],"4(b)":["4-b-1.png"],"5(a)":["5-a-1.png"],"5(b)":["5-b-1.png"],"5(c)":["5-c-1.png"],"5(d)(i)":["5-d-i-1.png"],"5(d)(ii)":["5-d-ii-1.png"],"6(a)":["6-a-1.png"],"6(b)":["6-b-1.png"],"6(c)(i)":["6-c-i-1.png"],"6(c)(ii)":["6-c-ii-1.png"],"6(c)(iii)":["6-c-iii-1.png"],"7(a)(i)":["7-a-i-1.png"],"7(a)(ii)":["7-a-ii-1.png"],"7(b)":["7-b-1.png"],"7(c)":["7-c-1.png","7-c-2.png"],"8(a)(i)":["8-a-i-1.png"],"8(a)(ii)":["8-a-ii-1.png"],"8(b)(i)":["8-b-i-1.png"],"8(b)(ii)":["8-b-ii-1.png"],"8(b)(iii)":["8-b-iii-1.png"],"8(b)(iv)":["8-b-iv-1.png"],"8(c)(i)":["8-c-i-1.png"],"8(c)(ii)":["8-c-ii-1.png"],"9(a)":["9-a-1.png","9-a-2.png"],"9(b)(i)":["9-b-i-1.png"],"9(b)(ii)":["9-b-ii-1.png"],"9(b)(iii)":["9-b-iii-1.png"],"9(b)(iv)":["9-b-iv-1.png"],"9(b)(v)":["9-b-v-1.png"]}};
// Visual source-page mapping. Each question is shown from the original Pearson PDF so diagrams, graphs, tables and photographs are preserved.
const visualMap={
 '1':{qp:[2],ms:[4]},'2(a)(i)':{qp:[3],ms:[5]},'2(a)(ii)':{qp:[3],ms:[5]},'2(b)':{qp:[4],ms:[6]},
 '3(a)':{qp:[5],ms:[7]},'3(b)(i)':{qp:[5],ms:[7]},'3(b)(ii)':{qp:[6],ms:[8]},
 '4(a)(i)':{qp:[7],ms:[9]},'4(a)(ii)':{qp:[7],ms:[9]},'4(b)':{qp:[8],ms:[10]},
 '5(a)':{qp:[9],ms:[11]},'5(b)':{qp:[9],ms:[11]},'5(c)':{qp:[10],ms:[12]},'5(d)(i)':{qp:[11],ms:[12]},'5(d)(ii)':{qp:[11,12],ms:[13]},
 '6(a)':{qp:[13],ms:[14]},'6(b)':{qp:[13],ms:[14]},'6(c)(i)':{qp:[14],ms:[15]},'6(c)(ii)':{qp:[14,15,16],ms:[15,16]},'6(c)(iii)':{qp:[16],ms:[16]},
 '7(a)(i)':{qp:[18],ms:[16]},'7(a)(ii)':{qp:[18],ms:[17]},'7(b)':{qp:[18],ms:[17]},'7(c)':{qp:[19,20,21],ms:[18,19]},
 '8(a)(i)':{qp:[22],ms:[20]},'8(a)(ii)':{qp:[23],ms:[20]},'8(b)(i)':{qp:[24],ms:[21]},'8(b)(ii)':{qp:[24],ms:[21]},'8(b)(iii)':{qp:[24,25],ms:[22]},'8(b)(iv)':{qp:[25],ms:[23]},'8(c)(i)':{qp:[26,27],ms:[24]},'8(c)(ii)':{qp:[27],ms:[25]},
 '9(a)':{qp:[28,29],ms:[26,27]},'9(b)(i)':{qp:[30],ms:[28]},'9(b)(ii)':{qp:[30],ms:[28]},'9(b)(iii)':{qp:[31],ms:[29]},'9(b)(iv)':{qp:[31],ms:[29]},'9(b)(v)':{qp:[32],ms:[30]}
};
const drawingQuestions=new Set(['6(a)']);
const app=document.getElementById('app');
const STORAGE_VERSION='v63clean';
const STATE_KEY='examTutorState_'+STORAGE_VERSION;
const DRAW_KEY='examTutorDrawings_'+STORAGE_VERSION;
const defaultState={view:'papers',paper:null,qi:0,answers:{},results:{},confidence:{}};
let state={...defaultState};
try{
  const saved=JSON.parse(localStorage.getItem(STATE_KEY)||'null');
  if(saved&&typeof saved==='object') state={...defaultState,...saved,answers:saved.answers||{},results:saved.results||{},confidence:saved.confidence||{}};
}catch(e){ state={...defaultState}; }
if(state.paper&&state.paper.id) state.paper=papers.find(p=>p.id===state.paper.id)||null;
let drawData={};
try{drawData=JSON.parse(localStorage.getItem(DRAW_KEY)||'{}')||{}}catch(e){drawData={}}
function persist(){
  try{localStorage.setItem(STATE_KEY,JSON.stringify({...state,paper:state.paper?{id:state.paper.id}:null}))}catch(e){}
}
function go(view){state.view=view;if(view==='papers'){state.paper=null;state.qi=0}persist();render()}
function openPaper(id){state.paper=papers.find(p=>p.id===id)||papers[0];state.view='questions';state.qi=0;persist();render()}
function openQ(i){state.qi=Math.max(0,Math.min(qs.length-1,Number(i)||0));state.view='viewer';persist();render()}
function prevQ(){if(state.qi>0){state.qi--;persist();render()}}
function nextQ(){if(state.qi<qs.length-1){state.qi++;persist();render()}}
function setConfidence(v){let key=state.paper.id+'-'+state.qi;state.confidence[key]=v;persist();render()}
function resetProgress(){if(!state.paper)return;let prefix=state.paper.id+'-';for(const k of Object.keys(state.answers))if(k.startsWith(prefix))delete state.answers[k];for(const k of Object.keys(state.results))if(k.startsWith(prefix))delete state.results[k];for(const k of Object.keys(state.confidence))if(k.startsWith(prefix))delete state.confidence[k];for(const k of Object.keys(drawData||{}))if(k.startsWith(prefix))delete drawData[k];localStorage.setItem(DRAW_KEY,JSON.stringify(drawData||{}));persist();render()}
function aiKey(){return sessionStorage.getItem('examTutorOpenRouterKey')||''}
function saveAiKey(){let e=document.getElementById('aiKey'),v=(e?.value||'').trim();if(!v)return alert('Paste your OpenRouter API key first.');sessionStorage.setItem('examTutorOpenRouterKey',v);render()}
function removeAiKey(){sessionStorage.removeItem('examTutorOpenRouterKey');render()}
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function qpFile(p){return p.id==='wbi11a-2601'?'biology-u1a-jan26-qp.pdf':'biology-u1-jan26-qp.pdf'}
function msFile(p){return p.id==='wbi11a-2601'?'biology-u1a-jan26-ms.pdf':'biology-u1-jan26-ms.pdf'}
function sourcePages(q,p,kind='qp'){
 let files=(cropMap[kind]?.[q.n]||[]); if(!files.length)return '';
 let dir=kind==='qp'?'question-images':'markscheme-images';
 let embedded=window.EXAM_TUTOR_IMAGES?.[kind]?.[q.n]||[];
 let full=kind==='qp'?qpFile(p):msFile(p);
 return files.map((file,i)=>{let src=embedded[i]||`${dir}/${file}`;return `<figure class="question-crop"><img src="${src}" alt="${kind==='qp'?'Original Pearson question':'Official Pearson mark scheme'} for ${q.n}" loading="eager" decoding="async" onerror="this.closest('figure').innerHTML='<div class=\'image-error\'>Image failed to load. Use the full PDF link below.</div>'"></figure>`}).join('')+`<a class="open-page" href="${full}" target="_blank">View full ${kind==='qp'?'question paper':'mark scheme'} ↗</a>`;
}
function drawingUI(key){
 return `<div class="draw-wrap"><div class="draw-tools"><b>Draw your answer</b><span>Mouse, trackpad or Apple Pencil</span><button class="secondary" onclick="undoDraw()">Undo</button><button class="secondary" onclick="clearDrawing()">Clear</button></div><canvas id="drawCanvas" class="draw-canvas" aria-label="Drawing answer"></canvas><div class="draw-hint"><b>Draw normally, just like on paper.</b> The AI checks only what is visibly present in your drawing against the Pearson marking points.</div></div>`;
}
let buildPieces={};
function triglycerideBuilder(key){
 const saved=drawData[key]?.builder||null;
 const pieces=saved||[
  {id:'g',t:'glycerol',x:12,y:36},
  {id:'f1',t:'fatty',x:70,y:18},{id:'f2',t:'fatty',x:70,y:45},{id:'f3',t:'fatty',x:70,y:72},
  {id:'b1',t:'bond',x:45,y:23},{id:'b2',t:'bond',x:45,y:50},{id:'b3',t:'bond',x:45,y:77}
 ]; buildPieces[key]=pieces;
 return `<div class="draw-wrap"><div class="draw-tools"><b>Build your triglyceride</b><span>Drag the exact exam shapes into the arrangement you would draw.</span><button class="secondary" onclick="resetBuilder()">Reset</button></div><div id="structureBoard" class="structure-board">${pieces.map(pieceHTML).join('')}</div><div class="draw-hint"><b>Accurate diagram marking:</b> this question is marked geometrically on your arrangement, not by AI. Scribbles/random shapes cannot receive marks.</div></div>`;
}
function pieceHTML(p){let label=p.t==='glycerol'?'glycerol':p.t==='fatty'?'fatty acid':'ester bond';return `<div class="chem-piece ${p.t}" data-id="${p.id}" style="left:${p.x}%;top:${p.y}%" title="${label}"><span>${label}</span></div>`}
function initBuilder(){let board=document.querySelector('#structureBoard');if(!board)return;let key=state.paper.id+'-'+state.qi;let pieces=buildPieces[key]||[];for(let el of board.querySelectorAll('.chem-piece')){el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);let r=board.getBoundingClientRect(),id=el.dataset.id,p=pieces.find(x=>x.id===id);let move=ev=>{let x=(ev.clientX-r.left)/r.width*100,y=(ev.clientY-r.top)/r.height*100;p.x=Math.max(2,Math.min(94,x));p.y=Math.max(4,Math.min(92,y));el.style.left=p.x+'%';el.style.top=p.y+'%'};let up=()=>{el.removeEventListener('pointermove',move);saveBuilder()};el.addEventListener('pointermove',move);el.addEventListener('pointerup',up,{once:true})}}}
function saveBuilder(){let key=state.paper.id+'-'+state.qi;drawData[key]={builder:buildPieces[key]||[]};localStorage.setItem(DRAW_KEY,JSON.stringify(drawData));}
function resetBuilder(){let key=state.paper.id+'-'+state.qi;delete drawData[key];delete buildPieces[key];localStorage.setItem(DRAW_KEY,JSON.stringify(drawData));render()}
function markTriglycerideBuilder(){let key=state.paper.id+'-'+state.qi,p=buildPieces[key]||drawData[key]?.builder||[];if(p.length!==7)return null;let g=p.find(x=>x.t==='glycerol'),fs=p.filter(x=>x.t==='fatty'),bs=p.filter(x=>x.t==='bond');if(!g||fs.length!==3||bs.length!==3)return {score:0,details:[{ok:false,text:'One glycerol, three fatty acids and three ester bonds must be shown.'}]};
 // Correct topology: glycerol left, each bond between glycerol and a fatty acid, three distinct vertical levels.
 fs.sort((a,b)=>a.y-b.y);bs.sort((a,b)=>a.y-b.y);let distinct=(fs[2].y-fs[0].y)>25&&(bs[2].y-bs[0].y)>25;let order=fs.every(f=>f.x>g.x+25)&&bs.every(b=>b.x>g.x+12&&b.x<Math.min(...fs.map(f=>f.x))+8);let aligned=fs.every((f,i)=>Math.abs(f.y-bs[i].y)<14);let criterion1=distinct;let criterion2=criterion1&&order&&aligned;let score=(criterion1?1:0)+(criterion2?1:0);return {score,details:[{ok:criterion1,text:criterion1?'One glycerol, three fatty acids and three ester bonds are represented.':'The required 1 glycerol + 3 fatty acids + 3 bonds are not arranged as three clear arms.'},{ok:criterion2,text:criterion2?'All three fatty acids are correctly connected to the glycerol through ester bonds.':'The components are not connected/aligned in the correct triglyceride arrangement.'}],feedback:score===2?'The structure satisfies both official marking points.':'Rearrange the pieces so the glycerol is on one side with three separate ester bonds leading to three fatty-acid chains.',improved:'One glycerol joined by three ester bonds to three fatty-acid chains.'};}
let strokes=[],currentStroke=null;
function initDrawing(){let c=document.querySelector('#drawCanvas');if(!c)return;let key=state.paper.id+'-'+state.qi;let dpr=window.devicePixelRatio||1,w=c.clientWidth,h=420;c.width=w*dpr;c.height=h*dpr;let ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';strokes=drawData[key]||[];redraw();let pos=e=>{let r=c.getBoundingClientRect(),pt=e.touches?e.touches[0]:e;return [pt.clientX-r.left,pt.clientY-r.top]};let start=e=>{e.preventDefault();currentStroke=[pos(e)];strokes.push(currentStroke);drawData[key]=strokes};let move=e=>{if(!currentStroke)return;e.preventDefault();currentStroke.push(pos(e));redraw()};let end=()=>{currentStroke=null;saveDrawing()};c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);window.addEventListener('pointerup',end,{once:false});}
function redraw(){let c=document.querySelector('#drawCanvas');if(!c)return;let ctx=c.getContext('2d'),dpr=window.devicePixelRatio||1;ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,c.width,c.height);ctx.restore();ctx.beginPath();for(let st of strokes){if(!st.length)continue;ctx.moveTo(st[0][0],st[0][1]);for(let i=1;i<st.length;i++)ctx.lineTo(st[i][0],st[i][1]);}ctx.stroke();}
function saveDrawing(){let c=document.querySelector('#drawCanvas');if(!c)return;let key=state.paper.id+'-'+state.qi;drawData[key]=strokes;localStorage.setItem(DRAW_KEY,JSON.stringify(drawData));persist();}
function undoDraw(){strokes.pop();saveDrawing();redraw()}function clearDrawing(){strokes=[];saveDrawing();redraw()}
function drawingStats(){let pts=strokes.reduce((n,s)=>n+s.length,0),len=0,minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const st of strokes){for(let i=0;i<st.length;i++){let [x,y]=st[i];minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);if(i){let [px,py]=st[i-1];len+=Math.hypot(x-px,y-py)}}}return {strokes:strokes.length,pts,len,bbox:(isFinite(minX)?[minX,minY,maxX,maxY]:null)};}
function validDrawingAttempt(){let d=drawingStats();return d.strokes>=2 && d.pts>=8 && d.len>=45;}
function canvasDataUrl(){let d=drawingStats();if(!d.bbox)return null;let [minX,minY,maxX,maxY]=d.bbox,pad=28;minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX+=pad;maxY+=pad;let w=Math.max(1,maxX-minX),h=Math.max(1,maxY-minY),scale=Math.min(1,640/Math.max(w,h));let out=document.createElement('canvas');out.width=Math.max(1,Math.round(w*scale));out.height=Math.max(1,Math.round(h*scale));let x=out.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,out.width,out.height);x.strokeStyle='#111';x.lineWidth=Math.max(2,3*scale);x.lineCap='round';x.lineJoin='round';for(const st of strokes){if(st.length<1)continue;x.beginPath();x.moveTo((st[0][0]-minX)*scale,(st[0][1]-minY)*scale);for(let i=1;i<st.length;i++)x.lineTo((st[i][0]-minX)*scale,(st[i][1]-minY)*scale);x.stroke()}return out.toDataURL('image/jpeg',0.78)}
function setupAI(){let existing=aiKey();return `<div class="ai-setup"><b>AI examiner setup</b><p class="ai-note">Connect an OpenRouter key to turn on semantic AI marking. The key is kept only in this browser tab/session in this prototype and is not included in the downloaded project.</p><input id="aiKey" type="password" autocomplete="off" placeholder="OpenRouter API key" value="${esc(existing)}"><button class="secondary" onclick="saveAiKey()">${existing?'Update key':'Connect AI'}</button>${existing?` <button class="danger-link" onclick="removeAiKey()">Disconnect</button>`:''}</div>`}
function schemeText(q){if(q.type==='mcq')return `Correct option: ${q.correct}.`;if(q.groups)return q.groups.map((g,i)=>`Accepted route ${i+1}: ${g.map(x=>x[0]).join(' | ')}`).join('\n');if(q.alts)return `Accept one of: ${q.alts.join('; ')}`;return (q.scheme||[]).map((x,i)=>`${i+1}. ${x[0]}`).join('\n')+(q.cap?`\nMaximum ${q.cap} marks.`:'')+(q.note?`\nExaminer guidance: ${q.note}`:'')}
function parseAIJson(raw){let t=String(raw||'').trim().replace(/^```(?:json)?/i,'').replace(/```$/,'').trim();let a=t.indexOf('{'),b=t.lastIndexOf('}');if(a>=0&&b>a)t=t.slice(a,b+1);return JSON.parse(t)}
function canvasDataUrl(){let d=drawingStats();if(!d.bbox)return null;let [minX,minY,maxX,maxY]=d.bbox,pad=28;minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);maxX+=pad;maxY+=pad;let w=Math.max(1,maxX-minX),h=Math.max(1,maxY-minY),scale=Math.min(1,640/Math.max(w,h));let out=document.createElement('canvas');out.width=Math.max(1,Math.round(w*scale));out.height=Math.max(1,Math.round(h*scale));let x=out.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,out.width,out.height);x.strokeStyle='#111';x.lineWidth=Math.max(2,3*scale);x.lineCap='round';x.lineJoin='round';for(const st of strokes){if(st.length<1)continue;x.beginPath();x.moveTo((st[0][0]-minX)*scale,(st[0][1]-minY)*scale);for(let i=1;i<st.length;i++)x.lineTo((st[i][0]-minX)*scale,(st[i][1]-minY)*scale);x.stroke()}return out.toDataURL('image/jpeg',0.78)}
function drawingStats(){let pts=strokes.reduce((n,s)=>n+s.length,0),len=0,minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const st of strokes){for(let i=0;i<st.length;i++){let [x,y]=st[i];minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);if(i){let [px,py]=st[i-1];len+=Math.hypot(x-px,y-py)}}}return {strokes:strokes.length,pts,len,bbox:(isFinite(minX)?[minX,minY,maxX,maxY]:null)};}
function validDrawingAttempt(){let d=drawingStats();return d.strokes>=2 && d.pts>=8 && d.len>=45;}
function embeddedImages(kind,q){return window.EXAM_TUTOR_IMAGES?.[kind]?.[q.n]||[]}
async function aiMark(){let p=state.paper,q=qs[state.qi],key=p.id+'-'+state.qi;
 let a=getAnswer(q,key);
 if(!a)return alert('Write, select, or draw an answer first.');
 if(q.type==='mcq'){mark();return;}
 if(drawingQuestions.has(q.n) && !validDrawingAttempt())return alert('There is not enough of a drawing to mark yet. Add the complete structure first.');
 let token=aiKey();if(!token)return alert('Connect your OpenRouter key in AI examiner setup first.');
 state.answers[key]=a;persist();let btn=document.querySelector('#aiMarkBtn');if(btn){btn.disabled=true;btn.textContent='AI examiner is marking…'}
 const normalSystem=`You are a strict Pearson Edexcel International A Level Biology examiner. Mark only from the supplied question-specific marking guidance. Apply ACCEPT/IGNORE/DO NOT ACCEPT logic when it is provided. Reward scientifically equivalent wording, but do not award a mark merely because a related keyword appears. Respect the maximum mark and any cap. Return ONLY valid JSON with keys score (integer), max_score (integer), awarded (array of short strings), missed (array of short strings), feedback (short string), improved_answer (concise exam-style answer).`;
 const drawingSystem=`You are a strict Pearson Edexcel Biology diagram examiner. Inspect ONLY the student's drawing image. Award a mark only when the required feature is clearly visible. Scribbles, random lines, ambiguous shapes, or features you cannot verify score 0. For Q6(a), mark exactly: M1 = one glycerol, three fatty acids and three ester-bond connections are visibly represented; M2 = all components are visibly joined in the correct triglyceride arrangement. M2 cannot be awarded unless M1 is met. Return JSON only: {\"score\":0,\"max_score\":2,\"criteria\":[{\"criterion\":\"M1\",\"met\":false,\"visible_evidence\":\"\"},{\"criterion\":\"M2\",\"met\":false,\"visible_evidence\":\"\"}],\"feedback\":\"\",\"improved_answer\":\"\",\"drawing_valid\":true,\"uncertain\":false}. If you cannot actually inspect the pixels, set drawing_valid=false and uncertain=true.`;
 const prompt=`Question ${q.n} (${q.marks} marks):\n${q.q}\n\nOfficial marking guidance:\n${schemeText(q)}\n\nStudent answer:\n${a}`;
 let userContent=prompt, system=normalSystem;
 if(drawingQuestions.has(q.n)){
   system=drawingSystem;let img=canvasDataUrl();
   userContent=[{type:'text',text:prompt+'\n\nThe single image below is the STUDENT DRAWING. Grade only visible features in this image. The official marking guidance is already provided as text above.'},{type:'image_url',image_url:{url:img}}];
 }
 try{
   let cfg=window.EXAM_TUTOR_AI||{};
   let controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
   let res=await fetch(cfg.endpoint||'https://openrouter.ai/api/v1/chat/completions',{method:'POST',signal:controller.signal,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json','X-Title':'Private Exam Tutor'},body:JSON.stringify({model:cfg.model||'inclusionai/ling-3.0-flash-vl:free',temperature:0,max_tokens:drawingQuestions.has(q.n)?160:420,messages:[{role:'system',content:system},{role:'user',content:userContent}],...(drawingQuestions.has(q.n)?{}:{response_format:{type:'json_object'}})})});clearTimeout(timer);
   let data=await res.json();if(!res.ok)throw new Error(data?.error?.message||`API error ${res.status}`);let raw=data?.choices?.[0]?.message?.content;if(!raw)throw new Error('The AI returned an empty response.');let j=parseAIJson(raw);
   let details,score;
   if(drawingQuestions.has(q.n)){
     if(j.drawing_valid===false || j.uncertain===true)throw new Error('The vision examiner could not verify the drawing reliably. No mark was saved.');
     let criteria=Array.isArray(j.criteria)?j.criteria:[];
     details=criteria.map(c=>({ok:c.met===true,text:`${c.criterion}${c.visible_evidence?' — visible evidence: '+c.visible_evidence:''}`}));
     score=details.filter(x=>x.ok).length;
     score=Math.min(score,q.marks,Math.max(0,Number(j.score)||0));
     if(!criteria.length)throw new Error('The vision examiner did not return criterion-by-criterion evidence. No mark was saved.');
   }else{score=Math.max(0,Math.min(q.marks,Number(j.score)||0));details=[...(j.awarded||[]).map(x=>({ok:true,text:x})),...(j.missed||[]).map(x=>({ok:false,text:x}))];}
   state.results[key]={score,details,answer:a,ai:true,feedback:j.feedback||'',improved:j.improved_answer||'',attemptedAt:Date.now()};persist();render();
 }catch(e){alert('AI marking could not run reliably: '+(e.name==='AbortError'?'The examiner did not respond within 30 seconds.':e.message)+'\n\nNo AI mark has been saved. Your answer/drawing is still here, and you can compare it with the official mark scheme.');render();}
}
function render(){ if(state.view==='papers') papersView(); else if(state.view==='questions') questionList(); else viewer(); }
function papersView(){app.innerHTML=`<div class="hero"><div><span class="eyebrow">YOUR STUDY STACKS</span><h1>What do you want to practise?</h1><p>Exam questions, instant marking and feedback from the official Pearson mark scheme.</p></div><div class="stat"><b>2</b><span>active stacks</span></div></div><div class="sectionTitle"><div><h2>Biology · Unit 1</h2><p>Molecules, Diet, Transport and Health</p></div></div><div class="paperGrid">${papers.map(p=>`<article class="paperCard" onclick="openPaper('${p.id}')"><div class="paperTop"><span class="subjectBadge">BIOLOGY</span><span class="ready">● Ready</span></div><h3>${p.title}</h3><p>${p.code}</p>${p.id==='wbi11a-2601'?'<p class="paper-note">01A uses the same assessment questions as 01; Pearson supplies a separate Answer Book.</p>':''}<div class="paperMeta"><span>${p.time}</span><span>${p.marks} marks</span></div><button class="primary">Open stack →</button></article>`).join('')}</div><div class="notice"><b>Marking source:</b> the supplied Pearson mark schemes. All questions from the January 2026 Unit 1 paper are now included. The original PDFs remain available inside each paper.</div>`}
function questionList(){let p=state.paper;app.innerHTML=`<button class="back" onclick="go('papers')">← Papers</button><div class="paperHeader"><div><span class="subjectBadge">BIOLOGY</span><h1>${p.title}</h1><p>${p.code} · ${p.time} · ${p.marks} marks</p></div><div class="pdfBtns"><a href="${p.qp}" target="_blank">Question paper ↗</a><a href="${p.ms}" target="_blank">Mark scheme ↗</a></div></div><div class="paper-tools"><span>${Object.keys(state.results).filter(k=>k.startsWith(p.id)).length} / ${qs.length} parts attempted</span><button class="secondary" onclick="resetProgress()">Reset paper progress</button></div><div class="questionList">${qs.map((q,i)=>{let r=state.results[p.id+'-'+i],c=state.confidence[p.id+'-'+i];return `<div class="qrow" onclick="openQ(${i})"><div class="qnum">${q.n}</div><div class="grow"><b>${q.q}</b><span>${q.marks} mark${q.marks>1?'s':''}${c?' · confidence: '+c:''}</span></div>${r?`<div class="miniScore">${r.score}/${q.marks}</div>`:'<div class="unattempted">Not attempted</div>'}<div class="chev">›</div></div>`}).join('')}</div>`}
function answerUI(q,key){if(drawingQuestions.has(q.n))return drawingUI(key);if(q.type==='mcq')return `<div class="choices">${q.options.map(o=>`<label><input type="radio" name="mcq" value="${o[0]}" ${state.answers[key]===o[0]?'checked':''}> <span>${o}</span></label>`).join('')}</div>`;return `<textarea id="ans" class="answer" placeholder="Write your exam answer here...">${esc(state.answers[key]||'')}</textarea>`}
function viewer(){let p=state.paper,q=qs[state.qi],key=p.id+'-'+state.qi,r=state.results[key];app.innerHTML=`<div class="viewer-nav"><button class="back" onclick="state.view='questions';persist();render()">← Questions</button><div><button class="secondary" onclick="prevQ()" ${state.qi===0?'disabled':''}>← Previous</button> <button class="secondary" onclick="nextQ()" ${state.qi===qs.length-1?'disabled':''}>Next →</button></div></div><div class="viewer"><section class="exam"><div class="examBar"><span>${p.code}</span><b>${q.marks} MARK${q.marks>1?'S':''}</b></div><div class="qn">Question ${q.n}</div><div class="source-title"><b>Actual exam question</b><span>Shown directly from your Pearson paper so every diagram, graph, table and photo stays intact.</span></div><div class="source-pages">${sourcePages(q,p,'qp')}</div><details class="typed-question"><summary>Text version</summary><div class="questionText">${q.q}</div></details>${answerUI(q,key)}<div class="confidence"><span>How confident are you?</span>${['Low','Medium','High'].map(v=>`<button data-v="${v}" class="${state.confidence[key]===v?'active':''}" onclick="setConfidence('${v}')">${v}</button>`).join('')}</div><div class="actions"><button class="primary" id="aiMarkBtn" onclick="aiMark()">✦ Mark with AI</button><button class="secondary" onclick="mark()">Local mark</button><button class="secondary" onclick="clearAns()">Clear</button></div>${r?resultHTML(r,q,p):''}</section><aside class="sidebar"><div class="sideCard"><span class="tiny">PAPER</span><b>${p.title}</b><p>${p.code}</p>${p.id==='wbi11a-2601'?'<p class="paper-note">01A uses the same assessment questions as 01; Pearson supplies a separate Answer Book.</p>':''}</div><div class="sideCard"><span class="tiny">PROGRESS</span><b>${Object.keys(state.results).filter(k=>k.startsWith(p.id)).length} / ${qs.length} parts attempted</b></div><div class="sideCard"><span class="tiny">QUESTION</span><b>${state.qi+1} of ${qs.length}</b><p>This build starts clean. New answers save only on this device.</p></div><div class="ai-status"><span class="ai-dot ${aiKey()?'':'off'}"></span>${aiKey()?'AI examiner connected':'AI examiner not connected'}</div>${setupAI()}<a class="sideLink" href="${p.qp}" target="_blank">Open original question paper ↗</a></aside></div>`;setTimeout(()=>{if(drawingQuestions.has(q.n))initDrawing()},0)}
function getAnswer(q,key){if(drawingQuestions.has(q.n)){saveDrawing();let hasInk=(drawData[key]||[]).length>0;return hasInk?'[DRAWING SUBMITTED]':''}if(q.type==='mcq'){let e=document.querySelector('input[name=mcq]:checked');return e?e.value:''}return document.querySelector('#ans')?.value.trim()||''}
function has(a,keys){a=a.toLowerCase().replace(/[–—]/g,'-');return keys.some(k=>a.includes(k))}
function mark(){let p=state.paper,q=qs[state.qi],key=p.id+'-'+state.qi,a=getAnswer(q,key);if(!a)return alert('Write or select an answer first.');if(drawingQuestions.has(q.n))return alert('Drawing questions are vision-marked only. Local keyword marking is disabled because it cannot inspect your diagram.');state.answers[key]=a;let score=0,details=[];
 if(q.type==='mcq'){score=a===q.correct?1:0;details=[{ok:score===1,text:score?'Correct answer.':`The credited answer is ${q.correct}.`}];}
 else if(q.groups){let best=[];for(const g of q.groups){let d=g.map(x=>({ok:has(a,x[1]),text:x[0]}));if(d.filter(x=>x.ok).length>best.filter(x=>x.ok).length)best=d}score=best.filter(x=>x.ok).length;details=best;}
 else if(q.alts){let ok=has(a,q.keys);score=ok?1:0;details=[{ok,text:ok?'Creditable answer.':`Credit requires one of: ${q.alts.join('; ')}.`}];}
 else {details=q.scheme.map(x=>({ok:has(a,x[1]),text:x[0]}));score=details.filter(x=>x.ok).length;if(q.cap)score=Math.min(score,q.cap);score=Math.min(score,q.marks)}
 state.results[key]={score,details,answer:a,attemptedAt:Date.now()};persist();render();}
function resultHTML(r,q,p){let full=r.score===q.marks;return `<div class="result"><div class="resultHead"><div><span class="tiny">MARK</span><div class="bigScore">${r.score}<small>/${q.marks}</small></div></div><div class="verdict ${full?'full':''}">${full?'Full marks':'Improve and retry'}</div></div><h3>Mark-scheme breakdown</h3>${r.details.map(d=>`<div class="point ${d.ok?'hit':'miss'}"><span>${d.ok?'✓':'×'}</span><div>${d.text}</div></div>`).join('')}${r.ai?`<div class="ai-feedback"><div class="ai-title">✦ AI examiner feedback</div><div class="ai-body"><h4>Feedback</h4><p>${esc(r.feedback)}</p><h4>Improved answer</h4><p>${esc(r.improved)}</p></div></div>`:''}${q.note?`<div class="guidance"><b>Examiner guidance</b><br>${q.note}</div>`:''}<div class="official-ms"><h3>Actual Pearson mark scheme</h3><p>This is the original mark-scheme page for this question.</p>${sourcePages(q,p,'ms')}</div><div class="post-actions"><button class="retry" onclick="document.querySelector('#ans')?.focus()">Edit answer & retry</button><button class="primary" onclick="nextQ()" ${state.qi===qs.length-1?'disabled':''}>Next question →</button></div></div>`}
function clearAns(){let p=state.paper,key=p.id+'-'+state.qi;delete state.answers[key];delete state.results[key];persist();render()}
render();
