const app=document.getElementById('app');
const papers=window.PSYCH_DATA||[];
const KEY='examTutorPsychV11';
let state={view:'papers',paperId:null,qi:0,answers:{},results:{}};
try{state={...state,...JSON.parse(sessionStorage.getItem(KEY)||'{}')}}catch(e){}
const save=()=>{try{sessionStorage.setItem(KEY,JSON.stringify(state))}catch(e){}};
const paper=()=>papers.find(p=>p.id===state.paperId)||null;
const q=()=>paper()?.questions?.[state.qi]||null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function apiKey(){return sessionStorage.getItem('examTutorOpenRouterKey')||''}
function setKey(){const v=(document.getElementById('apiKey')?.value||'').trim();if(v){sessionStorage.setItem('examTutorOpenRouterKey',v);render()}}
function openPaper(id){state.paperId=id;state.qi=0;state.view='list';save();render()}
function openQ(i){state.qi=i;state.view='viewer';save();render()}
function home(){location.href='index.html'}
function back(){state.view=state.view==='viewer'?'list':'papers';save();render()}
function resetPaper(){const pre=state.paperId+'-';for(const o of [state.answers,state.results])for(const k of Object.keys(o))if(k.startsWith(pre))delete o[k];save();render()}
function key(){return state.paperId+'-'+state.qi}
function answer(){return document.getElementById('answer')?.value?.trim()||''}
function saveAnswer(){const a=document.getElementById('answer')?.value??'';state.answers[key()]=a;save()}
function paperView(){
 app.innerHTML=`<button class="back" onclick="home()">← Biology / home</button><div class="hero"><div><span class="eyebrow">PSYCHOLOGY · v11 PSYCH EXAMINER</span><h1>WPS01 · Social & Cognitive Psychology</h1><p>Six complete exam-series stacks with Pearson-specific AO and levels-based marking.</p></div><div class="stat"><b>${papers.length}</b><span>paper stacks</span></div></div><div class="psych-note"><b>Psychology marking:</b> short answers are marked against the exact paper-specific scheme. 8- and 12-mark responses are judged holistically against that question's Pearson level descriptors, AO balance, command word, application and conclusion/judgement requirements.</div><div class="paperGrid">${papers.map(p=>`<article class="paperCard" onclick="openPaper('${p.id}')"><div class="paperTop"><span class="subjectBadge">PSYCHOLOGY</span><span class="ready">● Ready</span></div><h3>${p.title}</h3><p>${p.code}</p><div class="paperMeta"><span>${p.time}</span><span>${p.marks} marks</span></div><button class="primary">Open stack →</button></article>`).join('')}</div>`;
}
function listView(){const p=paper();app.innerHTML=`<button class="back" onclick="back()">← Psychology papers</button><div class="paperHeader"><div><span class="subjectBadge">PSYCHOLOGY</span><h1>${p.title}</h1><p>${p.code} · ${p.time} · ${p.marks} marks</p></div><div class="pdfBtns"><a href="${p.qp}" target="_blank">Question paper ↗</a><a href="${p.ms}" target="_blank">Mark scheme ↗</a></div></div><div class="paper-tools"><span>${Object.keys(state.results).filter(k=>k.startsWith(p.id+'-')).length} / ${p.questions.length} markable parts attempted</span><button class="secondary" onclick="resetPaper()">Reset paper</button></div><div class="questionList">${p.questions.map((x,i)=>{const r=state.results[p.id+'-'+i];return `<div class="qrow" onclick="openQ(${i})"><div class="qnum">${x.n}</div><div class="grow"><b>Question ${x.n}${x.extended?' · Levels-based':''}</b><span>${x.marks} mark${x.marks!==1?'s':''}${x.drawing?' · manual graph/drawing mark':''}</span></div>${r?`<div class="miniScore">${r.score}/${x.marks}</div>`:'<div class="unattempted">Not attempted</div>'}<div class="chev">›</div></div>`}).join('')}</div>`}
function sourcePath(p,x,kind){return `psych-pages/${p.id}-${kind}-p${kind==='qp'?x.qpPage:x.msPage}.png`}
function sourceImage(p,x,kind,alt){const src=sourcePath(p,x,kind);return `<img class="psych-source" src="${src}" alt="${alt}" onerror="sourceFallback(this,'${kind}','${kind==='qp'?x.qpPage:x.msPage}')">`}
function sourceFallback(img,kind,page){const p=paper();const pdf=kind==='qp'?p.qp:p.ms;img.outerHTML=`<div class="image-error"><b>${kind==='qp'?'Question':'Mark scheme'} preview could not load.</b><br><a class="open-page" href="${pdf}#page=${page}" target="_blank">Open the exact Pearson page ↗</a></div>`}
function viewer(){const p=paper(),x=q(),k=key(),r=state.results[k],a=state.answers[k]||'';const extended=x.extended?`<div class="psych-note"><span class="level-badge">Levels-based ${x.marks}-marker</span> Marked using this paper's Pearson AO split and level descriptors — not keyword counting.</div>`:'';app.innerHTML=`<div class="viewer-nav"><button class="back" onclick="back()">← Questions</button><div><button class="secondary" ${state.qi===0?'disabled':''} onclick="state.qi--;save();render()">← Previous</button><button class="secondary" ${state.qi===p.questions.length-1?'disabled':''} onclick="state.qi++;save();render()">Next →</button></div></div><div class="paperHeader"><div><span class="subjectBadge">PSYCHOLOGY</span><h1>Question ${x.n}</h1><p>${p.title} · ${x.marks} marks</p></div><div class="pdfBtns"><a href="${p.qp}#page=${x.qpPage}" target="_blank">Full paper ↗</a></div></div>${extended}<div class="psych-viewer"><section class="psych-exam"><div class="psych-question-frame">${sourceImage(p,x,'qp','Original Pearson question page')}</div><div id="schemeBox" class="psych-ms" hidden><h3>Official Pearson mark scheme</h3>${sourceImage(p,x,'ms','Official Pearson mark scheme page')}</div>${r?resultBox(r,x):''}</section><aside class="psych-side"><h3>Your answer</h3><p>${x.extended?'Write the full exam response here. The box is deliberately larger for the extended response.':'Answer exactly as you would in the exam.'}</p><textarea class="psych-answer ${x.extended?'extended':''}" id="answer" oninput="saveAnswer()" placeholder="Write your exam answer here…">${esc(a)}</textarea>${x.drawing?manualBox(x):`<div class="actions"><button class="primary" id="markBtn" onclick="markAI()">✦ Mark answer</button><button class="secondary" onclick="toggleScheme()">Show scheme</button></div>`}${!apiKey()&&!x.drawing?`<div class="psych-note"><b>AI examiner setup</b><br><input id="apiKey" type="password" placeholder="OpenRouter key" style="width:100%;margin:8px 0;padding:11px;border:1px solid #cfd4de;border-radius:9px"><button class="secondary" onclick="setKey()">Connect</button></div>`:''}</aside></div>`}
function toggleScheme(){const b=document.getElementById('schemeBox');if(!b)return;b.hidden=!b.hidden;if(!b.hidden)b.scrollIntoView({behavior:'smooth',block:'start'})}
function manualBox(x){return `<div class="psych-note"><b>Graph/drawing question:</b> AI marking is disabled. Complete it on paper or in the PDF, reveal the Pearson scheme, then self-mark.</div><div class="actions"><button class="primary" onclick="toggleScheme()">Show Pearson scheme</button></div><div class="manual-score">${Array.from({length:x.marks+1},(_,i)=>`<button class="secondary" onclick="selfMark(${i})">${i}/${x.marks}</button>`).join('')}</div>`}
function selfMark(s){state.results[key()]={score:s,self:true};save();render()}
function resultBox(r,x){const ao=r.ao||{};return `<div class="resultCard"><div class="scoreBig">${r.score}/${x.marks}</div>${r.level?`<p><span class="level-badge">Level ${esc(r.level)}</span></p>`:''}${x.extended?`<div class="ao-grid"><div class="ao-card"><b>AO1</b><br>${esc(ao.AO1||'—')}</div><div class="ao-card"><b>AO2</b><br>${esc(ao.AO2||'—')}</div><div class="ao-card"><b>AO3</b><br>${esc(ao.AO3||'—')}</div></div>`:''}${r.awarded?.length?`<h3>What earned credit</h3><ul>${r.awarded.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}${r.missed?.length?`<h3>What is missing</h3><ul>${r.missed.map(v=>`<li>${esc(v)}</li>`).join('')}</ul>`:''}${r.why?`<h3>${x.extended?'Why this level/mark':'Examiner reasoning'}</h3><p>${esc(r.why)}</p>`:''}${r.next?`<h3>Highest-value improvement</h3><p>${esc(r.next)}</p>`:''}${r.improved?`<h3>Full-mark model</h3><p>${esc(r.improved)}</p>`:''}<button class="secondary" onclick="toggleScheme()">Compare with Pearson scheme</button></div>`}
function line(t,n){const m=t.match(new RegExp('(?:^|\\n)'+n+'\\s*:\\s*(.*)','i'));return m?m[1].trim():''}
function split(v){return String(v||'').split(/\s*\|\s*/).map(s=>s.trim()).filter(s=>s&&!/^(none|n\/a|—)$/i.test(s))}
async function markAI(){const x=q(),a=answer();if(!a)return alert('Write an answer first.');const token=apiKey();if(!token)return alert('Connect your OpenRouter key first.');saveAnswer();const b=document.getElementById('markBtn');if(b){b.disabled=true;b.textContent='Marking…'}
 const command=(x.questionContext.match(/\b(Evaluate|Assess|Discuss|Explain|Describe|State|Calculate|Give|To what extent)\b/i)||[])[1]||'Answer';
 const levelRules=x.extended?`THIS IS A PEARSON LEVELS-BASED ${x.marks}-MARK RESPONSE. Do NOT point-count. Apply the exact level descriptor supplied below holistically. Respect its AO split. Command word is ${command}. For EVALUATE, require developed evaluation and an evidence-supported conclusion for the top level. For ASSESS/TO WHAT EXTENT, require developed judgements about significance/value, not merely a list of strengths and weaknesses. For DISCUSS, judge balanced developed discussion and application where the scheme requires AO2; a final conclusion is not automatically required. Scenario/application marks require explicit use of the scenario; generic material cannot substitute for AO2. A top-level response must sustain the required qualities across the answer, not show them once.`:`This is a short-answer question. Award only credit supported by the exact scheme. Respect AO1/AO2/AO3, scenario application, operationalisation, linked justification, calculation working, caps and generic-answer restrictions.`;
 const prompt=`You are a strict Pearson Edexcel IAL Psychology WPS01 examiner. ${levelRules}\n\nTARGET QUESTION: ${x.n} (${x.marks} marks)\nQUESTION-PAPER CONTEXT:\n${x.questionContext}\n\nEXACT QUESTION-SPECIFIC PEARSON MARK-SCHEME EXTRACT:\n${x.scheme}\n\nSTUDENT ANSWER:\n${a}\n\nMark positively but never invent meaning. Credit alternative valid wording only where the Pearson scheme allows reasonable alternatives. Never award a scenario/application mark for a generic answer. For linked 2-mark points, do not award the justification mark unless the identification/application it develops is creditworthy. For calculations, check the final value and any required working/rounding.\n\nReturn ONLY labelled lines, concise but specific.\nSCORE: integer 0-${x.marks}\nLEVEL: ${x.extended?'1, 2, 3 or 4':'N/A'}\nAO1: concise judgement or N/A\nAO2: concise judgement or N/A\nAO3: concise judgement or N/A\nAWARDED: evidence from the student's wording -> why it earns credit; separate items with |\nMISSED: exact missing/developable requirements; separate with |\nWHY_LEVEL: ${x.extended?'why the response fits this level and not the level above':'brief examiner reasoning'}\nNEXT: single highest-value change\nIMPROVED: concise full-mark answer that fits this exact question and scheme`;
 const models=x.extended?['inclusionai/ling-3.0-flash-fin:free','nvidia/nemotron-3-ultra-550b-a55b:free','openrouter/free']:['inclusionai/ling-3.0-flash-fin:free','nvidia/nemotron-3.5-lightning:free','openrouter/free'];
 const endpoint=(window.EXAM_TUTOR_AI||{}).endpoint||'https://openrouter.ai/api/v1/chat/completions';let last;
 for(let i=0;i<models.length;i++){try{if(b)b.textContent=i?'Retrying examiner…':'Marking…';const c=new AbortController(),timer=setTimeout(()=>c.abort(),i?17000:13000);let res;try{res=await fetch(endpoint,{method:'POST',signal:c.signal,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','HTTP-Referer':location.origin,'X-Title':'Private Exam Tutor'},body:JSON.stringify({model:models[i],temperature:0,max_tokens:x.extended?720:480,provider:{sort:'latency',allow_fallbacks:true},messages:[{role:'user',content:prompt}]})})}finally{clearTimeout(timer)}if(!res.ok)throw new Error('OpenRouter '+res.status);const d=await res.json();const t=typeof d?.choices?.[0]?.message?.content==='string'?d.choices[0].message.content:'';const num=Number((line(t,'SCORE').match(/\d+/)||[])[0]);if(!Number.isFinite(num))throw new Error('Incomplete examiner response');const awarded=split(line(t,'AWARDED')),missed=split(line(t,'MISSED'));if(num>0&&!awarded.length)throw new Error('Inconsistent examiner response');const rr={score:Math.max(0,Math.min(x.marks,Math.round(num))),level:x.extended?line(t,'LEVEL').match(/[1-4]/)?.[0]:'',ao:{AO1:line(t,'AO1'),AO2:line(t,'AO2'),AO3:line(t,'AO3')},awarded,missed,why:line(t,'WHY_LEVEL'),next:line(t,'NEXT'),improved:line(t,'IMPROVED')};state.results[key()]=rr;save();render();return}catch(e){last=e}}
 if(b){b.disabled=false;b.textContent='✦ Mark answer'}alert('Marking did not complete. Your answer is still saved in this tab, so retry.\n\n'+(last?.message||'Examiner unavailable.'))}
function render(){if(!state.paperId||state.view==='papers')paperView();else if(state.view==='list')listView();else viewer()}
render();
